#!/bin/bash
# bitcoin-tx is an offline tool and does not accept -datadir.
. "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/config.sh"
"$BITCOIN_PORTABLE_DIR/setup"
BITCOIN_PORTABLE_NICE_EXEC "$(basename "$0")" "$@"
