#!/bin/bash
. "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/config.sh"
"$BITCOIN_PORTABLE_DIR/setup"
BITCOIN_PORTABLE_NICE_EXEC bitcoin-qt -datadir="$(BITCOIN_PORTABLE_GET_PATH "$BITCOIN_PORTABLE_DIR/data")" "$@"
