#!/bin/bash

at="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
. "$at/config.sh"

src="$BITCOIN_CORE_URL"
dir="bitcoin-$BITCOIN_CORE_VERSION-$BITCOIN_CORE_OS"
tgz="$dir.tar.gz"

if [ ! -r "$at/$tgz" ]
then
    /bin/rm -rf "$at/$tgz"
    /bin/rm -rf "$at/$tgz.in-progress"
    /bin/rm -rf "$at/$dir"
    /bin/rm -rf "$at/bitcoin-$BITCOIN_CORE_OS"    
    curl -o "$at/$tgz.in-progress" "$BITCOIN_CORE_URL"
    mv "$at/$tgz.in-progress" "$at/$tgz"
fi

if [ ! -d "$at/$dir" ]
then
    /bin/rm -rf "$at/$dir"
    /bin/rm -rf "$at/$dir.in-progress"
    /bin/rm -rf "$at/bitcoin-$BITCOIN_CORE_OS"    
    mkdir -p "$at/$dir.in-progress"
    tar --strip-components=1 -zvxf "$at/$tgz" -C "$at/$dir.in-progress"
    mv "$at/$dir.in-progress" "$at/$dir"	
fi

mkdir -p "$at/data"




