name: Cross-Platform Test

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up environment for ARM (if applicable)
        if: ${{ matrix.arch == 'arm64' }}
        run: |
          # If you have any ARM-specific setup, it can go here
          echo "ARM-specific setup complete."

      - name: Run tests
        env:
          PLATFORM: ${{ matrix.arch }}
        run: |
          chmod +x ./test
          ./test
        shell: bash
